# Generated by Django 4.1.7 on 2023-03-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpiShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=15, verbose_name='Наименование')),
                ('desc', models.CharField(max_length=100, verbose_name='Описание сущности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Элемент сущности',
                'verbose_name_plural': 'Список сущностей',
            },
        ),
        migrations.CreateModel(
            name='NsiDudlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, verbose_name='Наименование')),
                ('code', models.CharField(max_length=2, verbose_name='Код')),
                ('m_ser', models.CharField(max_length=10, verbose_name='Маска серии')),
                ('m_num', models.CharField(max_length=15, verbose_name='Маска номера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='NsiMpiPolisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип полиса',
                'verbose_name_plural': 'Типы полисов',
            },
        ),
        migrations.CreateModel(
            name='NsiSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=15, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.AlterModelOptions(
            name='mpimethods',
            options={'verbose_name': 'Метод МПИ', 'verbose_name_plural': 'Методы МПИ'},
        ),
        migrations.AlterField(
            model_name='mpimethods',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='mpimethods',
            name='meth_desc',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mpimethods',
            name='meth_name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='mpimethods',
            name='mpi_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpi.mpiservices', verbose_name='Сервис МПИ'),
        ),
    ]
